candidate_name = ["Amit", "Neha", "Rahul", "Srinivas"]
print(f"Initial Queue: {candidate_name}")
candidate_name.append("Jagruthi")
print(f"Standard Arrival(added Jagruthi): {candidate_name}")
candidate_name.insert(0,"Durga")
print(f"VIP Insertion(added Durga at index 0): {candidate_name}")
total_applicants = len(candidate_name)
print(f"\nTotal waiting applicants:{total_applicants}")
print("\n--- Processing Queue Updates ---")
left_name = candidate_name.pop()
print(f"Candidate at the end of the queue left: {left_name}")
print(f"Current Queue:{candidate_name}")
called_candidate = candidate_name.pop(0) 
print(f"Called for interview (from the front): {called_candidate}")
print(f"Current Queue: {candidate_name}")
next_batch = candidate_name[0:2]  # Pulls index 0 and 1 (Amit and Neha)

print("\n--- Batch Extraction ---")
print(f"Next Batch for Interview: {next_batch}")
print(f"Main Line Remaining (Unmodified by slice): {candidate_name}")